### ISSUE TITLE
No features found for this entity

### ISSUE THREAD

**Issue by VedantaBabaria** [siacs/HttpUploadComponent#17]
I have successfully installed HttpUploadComponent on my server and done the necessary changes in configuration files , In my xmpp server under the external components tab it is showing successfully connected, but i am getting the below debug log because of which i am not able to see the file sharing icon in conferences tab in conversations 1.5.0.

Logs :
--------
-bash-3.2# python server.py
DEBUG    Loaded Plugin: XEP-0030: Service Discovery
DEBUG    Loaded Plugin: upload files via http
DEBUG    Connecting to localhost:5347
DEBUG    DNS: Querying localhost for AAAA records.
DEBUG    DNS: Querying localhost for A records.
DEBUG    Connecting to [::1]:5347
DEBUG    Event triggered: socket_error
ERROR    Could not connect to [::1]:5347. Socket Error #128: Network is unreachable
DEBUG    Connecting to 127.0.0.1:5347
DEBUG    Event triggered: connected
DEBUG     ==== TRANSITION disconnected -> connected
DEBUG    Starting HANDLER THREAD
DEBUG    Loading event runner
DEBUG    SEND (IMMED): <stream:stream xmlns="jabber:component:accept" xmlns:stream="http://etherx.jabber.org/streams" to='uploadComp'>
connected
DEBUG    RECV: <stream:stream from="uploadComp.example.com" id="2164828e">
DEBUG    SEND (IMMED): <handshake xmlns="jabber:component:accept">6485432218eb5d47bc3b75380adb9ce891dea76c</handshake>
DEBUG    RECV: <handshake />
DEBUG    Event triggered: session_bind
DEBUG    Event triggered: session_start
DEBUG    RECV: <iq from="component.example.com" type="get" id="860-7798" to="uploadcomp.example.com"><query xmlns="http://jabber.org/protocol/disco#info" /></iq>
DEBUG    Received disco info query from <component.example.com> to <uploadcomp.example.com>.
DEBUG    No identity found for this entity. Using default component identity.
DEBUG    No features found for this entity. Using default disco#info feature.
DEBUG    SEND: <iq from="uploadcomp.example.com" type="result" id="860-7798" to="component.example.com"><query xmlns="http://jabber.org/protocol/disco#info"><identity category="component" type="generic" /><feature var="http://jabber.org/protocol/disco#info" /></query></iq>
DEBUG    Scheduled event: Session timeout check: ()
requesting file: ./manager/html

-----------------------------------------------------------------------------------------------------------------------
Please Help

**Comment by iNPUTmice** [comment]
Did you relogin?

**Comment by VedantaBabaria** [comment]
Ya i tried to relogin again , but no luck.

**Comment by iNPUTmice** [comment]
is your server advertising the component as a disco item?

**Comment by VedantaBabaria** [comment]
Don't have much idea  but according to the logs : No features found for this entity. Using default disco#info feature , after this message it is advertising it as disco item.

**Comment by iNPUTmice** [comment]
That's something your xmpp has to do. Not the component. So there is no point in looking at the components log to answer the question on whether or not your xmpp server is advertising the component as a disco item.

**Comment by VedantaBabaria** [comment]
Can you share the http component logs , what is shows if it is properly installed and if converstaions 1.5.0 is successfully able to retrieve that feature.

**Comment by VedantaBabaria** [comment]
Is this component working with openfire 3.9.3 , Need Help

**Comment by andersruneson** [comment]
You probably want to change component port for openfire. Not sure it works
anyway though.

**Comment by VedantaBabaria** [comment]
Tried changing the port still getting the same message in the logs 

Please find the attached sceenshot and the message mark in red.

![http component log](https://cloud.githubusercontent.com/assets/12424938/9021711/38c7a5a8-386f-11e5-8f69-5cff41428ac7.JPG)

**Comment by iNPUTmice** [comment]
Hi,

please understand that this is an issue tracker meant to keep track of bugs (or feature suggestions) in a the HttpUploadComponent. This is not a support forum offering free support. If you would like to purchase professional support please refer to the the box 'Need Professional Support?' on our website http://conversations.im/#support

**Comment by VedantaBabaria** [comment]
Thanks
