### ISSUE TITLE
Exception [Errno 32] with small files

### ISSUE THREAD

**Issue by Lykos153** [siacs/HttpUploadComponent#18]
I'm trying this component on ArchLinux with a prosody0.10 on the same host. Some images _always_ result in the exception below, others do never. The only difference that I found is the file size: All images that were successfully transmitted had >= 5KiB while all images that failed had <= 3KiB. It's 100% reproducible. Is this due to a local problem on my host or has anybody else experienced this issue?

<pre>
[24/Jul/2015 15:32:28] "PUT /xx/xx/xx.webp HTTP/1.0" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.2.3', 51813)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
</pre>

Edit: Maybe I should mention that the component is behind an ngnix reverse proxy on a different host in the same LAN.

**Comment by SamWhited** [comment]
At a guess this has to do with the way files are being read from the socket; there's a weird chunking thing going on that reads 4096 bytes at a time that I haven't quite figured out. If the file is under 4096 bytes, the very first read will fail.

[See Line 124](https://github.com/siacs/HttpUploadComponent/blob/2678c0d2b83f7d54eaddf85097e51f986c2fe799/server.py#L124)

which should instead read:

````pyton
data = self.rfile.read(min(4096, len(data)))
````

**Comment by iNPUTmice** [comment]
```data = self.rfile.read(min(4096,remaining))```

probably then.

whats wrong with the chunking @SamWhited I'm trying to avoid loading the entire file into RAM... or am i missunderstanding how python works here?

**Comment by SamWhited** [comment]
> whats wrong with the chunking @SamWhited I'm trying to avoid loading the entire file into RAM... or am i missunderstanding how python works here?

I can't vouche for WIndows, but as is on Linux and BSD based systems (including OSX) I think you're writingthe entire file to ram anyways; write doesn't actually write to disk, it writes to the file buffer in memory. The file is only written to disk when `flush` is called (which happens in this case when the file is closed or when the kernel decides that it's low on memory or something and should be written to disk).

Nothing really wrong with chunking though, I'm just not sure that it's doing what you think it is. I'm not sure if this advise is really correct in all cases or not, but I generally tell people not to mess with file read / writes and just to do it and let the system handle it; it probably knows better than you, and in the worst case you may end up fighting the system file handling logic and making writes slower.

**Comment by iNPUTmice** [comment]
I'm not talking about the write I'm talking about the read from the socket.

i'm afraid that when I do self.rfile.read() it will first load the result into RAM. plus when doing the 'buffered' variant I can abort the file transfer as soon as I detect that the file size is too large. / larger than advertised.

**Comment by SamWhited** [comment]
yah, fair enough, disregard everything I just said. Chunked reading from the socket is definitely not a bad idea (assuming the fixed block size is fixed). I just looked, and your write is not flushhing either, so I think you're doing it correctly in general. My bad.

**Comment by iNPUTmice** [comment]
should be fixed in 96b39250b2843333f24c622b9b57f5242ec67ba3
