### ISSUE TITLE
Should `limit_except GET` work as-is in the contrib/nginx_site_example file?

### ISSUE THREAD

**Issue by deoren** [siacs/HttpUploadComponent#32]
I still consider myself a nginx newbie, so my apologies if the solution to this is immediately obvious, but during my testing the nginx setup as shown in 0dd07d316a5 does not work with the `limit_except` directive used as shown. The conf however works just fine if I omit the `limit_except` directive and just pass requests to the HttpUploadComponent.

In both cases I could see in the nginx log where a GET request was being made, so this struck me as odd as my understanding was that `limit_except GET` was supposed to limit _other_ requests aside from `GET`. What further confused me was that PUT requests (with the configuration shown in 0dd07d316a5) seemed to be allowed (code 200) as the files would show up on the filesystem with correct ownership and would be intact.

I'm running Ubuntu 14.04 and the upstream nginx 1.8.0-~trusty package that the nginx devs provide. My setup is only minimally changed from 0dd07d316a5 as shown below.

Here are the relevant values in my config.yml file:

```
storage_path : /var/lib/prosody/http_upload/

# 20MiB
max_file_size: 20971520

http_address: 127.0.0.1
http_port: 8080

# Do NOT use a sub-URI here as it does not appear to be supported
# DO explicitly specify the port, otherwise PUT requests result in 404 errors
get_url : https://upload.im.example.org:443
put_url : https://upload.im.example.org:443
```

and here is the nginx conf file:

```
server {
    listen 443 ssl;
    server_name  upload.im.example.org;

    # cert has multiple SANs entries, one of which is upload.im.example.org
    ssl_certificate      /etc/ssl/certs/im.example.org_server.crt;
    ssl_certificate_key  /etc/ssl/certs/im.example.org_server.key;

    root /var/lib/prosody/http_upload;

    location / {

        # Match 'max_file_size' from config.yml
        client_max_body_size 20m;

        charset          utf-8;
        add_header       Strict-Transport-Security "max-age=31536000; includeSubdomains";
        add_header       X-Frame-Options           DENY;

        limit_except GET {
            proxy_pass       http://127.0.0.1:8080;
        }

        proxy_set_header Host        $host;
        proxy_buffering off;
        tcp_nodelay on;

    }

}
```

**Comment by SamWhited** [comment]
> as my understanding was that limit_except GET was supposed to limit other requests aside from GET

That's correct; everything other than GET's (and, implicitly, HEAD's) will be passed to the component. However, in this config, nginx will serve GET requests directly (no need to proxy through to the component when we're just serving up files, which nginx is probably much better at).

I think Daniel likes to keep this as an issue tracker, and not a support forum. You might want to join conversations@conference.siacs.eu` if you have futher questions.

**Comment by deoren** [comment]
@SamWhited Thanks for the response. In my ignorance I couldn't say for sure that the provided example conf was broken, but I wanted to suggest that it could be. I wanted to offer as much supporting detail as I could to illustrate the problem I was running into to help Daniel (or yourself) be able to easily determine whether that was the case.

Thanks for the suggestion of joining the conference.

**Comment by deoren** [comment]
@SamWhited I'm a dummy.

nginx failed to properly access the content from `/var/lib/prosody/http_upload/` directly because it didn't have access to the `/var/lib/prosody/http_upload/` directory, specifically `/var/lib/prosody` because it is the home directory for the prosody user and thus secured to only allow owner and group access, not "other".

Once I (consciously) configured a location to allow nginx read-only access and the component read-write access the example configuration worked as intended. This was completely user error.

Sorry for the bad report. My only defense is that I meant well. :|
