### ISSUE TITLE
Namespace differs from XEP-0363

### ISSUE THREAD

**Issue by grigoryfedorov** [siacs/HttpUploadComponent#51]
Hi! I'm writing client implementation of XEP-0363 to work with you server component. 
It looks strange for me, that namespace used by you project ("eu:siacs:conversations:http:upload") differs from "urn:xmpp:http:upload" described in XEP-0363 (http://xmpp.org/extensions/xep-0363.html).
I think it may result in conflicts with some future implementations of this XEP.

**Comment by iNPUTmice** [comment]
This was fixed in 934c6e4ed60424c02c26e2801b42159ccaadddf6 a couple of days ago.

**Comment by grigoryfedorov** [comment]
Thanks!
