### ISSUE TITLE
When HttpUploadComponent is enabled many ejabberd feature stop randomly working

### ISSUE THREAD

**Issue by alexara** [siacs/HttpUploadComponent#56]
Hi!

I have ejabberd 15.07 installed with all relevant XEPs activated. Conversation 1.6.10 confirms that in the sever info.
When I start the HttpUploadComponent server with "python3 sever.py" something very strange happens:
XEPs are randomly disabled when a client (re)connects. It most happens to PEP, Carbon, MAM and to HttpUpload itself.
When the server is stopped everything is fine again.

Since an error occurs when I try to attach a TXT here and github strips away everything with looks like a tag I also uploaded everything on slexy.org: 

Server start and error message: http://slexy.org/view/s2g3TeQDJg
HttpUploadComponent config: http://slexy.org/view/s218z0Ct93
Ejabberd 15.07 config: http://slexy.org/view/s2nXxZQhbq

What could it be? Do you need more information? Can you reproduce it? 

Kind Regards

**Comment by gakwaya** [comment]
Hello ,
I see that you have been successful  at getting HttpUploadComponent  to work with ejabberd.Would you like to share on how to get this running for less experienced users?
1.How do I install this on my server ( I am running ubuntu 14.04LTS and ejabberd15.11)

2.What steps need to be taken on the client side : I found a simple demo ejabberd.yml configuration file here https://bitbucket.org/snippets/SamWhited/r9LEo/ejabberd-httpuploadcomponent-setup but I am still unsure what I need to do on the client side to get this working.

My goal : to be able to send Images and files in conferences like in one to one chat.

Thanks.

**Comment by thundergreen** [comment]
@gakwaya maybe u wanna join us in the help channel also Ejabberd? I recommend using Ejabberd httpupload component  join me/us @ ejabberd@conference.jabber.ru don't u worry we all speak English ;)
