### ISSUE TITLE
Don't always force downloading files

### ISSUE THREAD

**Issue by QuentinC** [siacs/HttpUploadComponent#7]
Hi,

I have a little suggestion:
When I've triied this with my friend, he told me that he would like images to open directly on the browser.
Right now, theses two lines: 
`self.send_header("Content-Type", 'application/octet-stream')
self.send_header("Content-Disposition", 'attachment; filename="{}"'.format(os.path.basename(filename)))`
makes browser download the file.

I think that they can be removed, at least for images types !

Don't you think that ?

Thanks !

**Comment by iNPUTmice** [comment]
feel free to send in a pull request that disables this for image files.

**Comment by yanntech** [comment]
Conversation send image in webp format but (my) python mimetypes was unable to guess the right mimetypes ( https://docs.python.org/2/library/mimetypes.html#mimetypes.guess_type ) even if I add image/webp in /etc/mimes.types
```bash
grep webp /etc/mime.types
image/webp					webp
```
in python:

```python
>>> import mimetypes
>>> mimetypes.knownfiles
['/etc/mime.types', '/etc/httpd/mime.types', '/etc/httpd/conf/mime.types', '/etc/apache/mime.types', '/etc/apache2/mime.types', '/usr/local/etc/httpd/conf/mime.types', '/usr/local/lib/netscape/mime.types', '/usr/local/etc/httpd/conf/mime.types', '/usr/local/etc/mime.types']
>>> mimetypes.suffix_map['.webp']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: '.webp'
>>> mimetypes.encodings_map['.webp']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: '.webp'
>>> mimetypes.types_map['.webp']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: '.webp'
```

The second way is to add a extension list...
