### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by paulapannell** [siacs/HttpUploadComponent#72]

**Comment by kriztan** [comment]
@paulapannell What are you going to tell us with an empty message?

**Comment by paulapannell** [comment]
I'm trying to recover all my messages

**Comment by kriztan** [comment]
I think you need not help for any of these repositorys but help for using github, please have a look here https://help.github.com/ and don't spam the issue trackers with senseless messages!

@iNPUTmice you can close this at this point.

**Comment by paulapannell** [comment]
Thank you
